const fs = require('fs');
const path = require('path');
const ejs = require('ejs');

const ROOT = path.join(__dirname, '..');
const TEMPLATES = path.join(ROOT, 'templates');
const PUBLIC = path.join(ROOT, 'public');
const OUT = path.join(__dirname, 'src', 'generated');

const includeRe = /<%- include\('([^']+)'(?:,\s*\{[^}]*\})?\)\s*%>/g;

function readTemplates(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) {
      readTemplates(full, out);
    } else if (name.endsWith('.ejs')) {
      const rel = path.relative(TEMPLATES, full).replace(/\\/g, '/').replace(/\.ejs$/, '');
      out[rel] = fs.readFileSync(full, 'utf8');
    }
  }
}

function splitArgs(str) {
  const pairs = [];
  let depth = 0, cur = '', i = 0;
  while (i < str.length) {
    const ch = str[i];
    if (ch === '(' || ch === '{') depth++;
    else if (ch === ')' || ch === '}') depth--;
    if (ch === ',' && depth === 0) {
      pairs.push(cur.trim());
      cur = '';
    } else cur += ch;
    i++;
  }
  if (cur.trim()) pairs.push(cur.trim());
  return pairs;
}

function inlinePartials(tpl, store) {
  let result = tpl;
  let guard = 0;
  const incRe = /<%- include\('([^']+)'(?:,\s*(\{(?:[^{}]|\{[^{}]*\})*\}))?\)\s*%>/g;
  while (incRe.test(result) && guard++ < 20) {
    result = result.replace(incRe, (match, name, args) => {
      if (!store[name]) throw new Error('missing partial: ' + name);
      let pre = '';
      if (args) {
        const inner = args.slice(1, -1);
        for (const pair of splitArgs(inner)) {
          const idx = pair.indexOf(':');
          if (idx === -1) continue;
          const key = pair.slice(0, idx).trim();
          const expr = pair.slice(idx + 1).trim();
          pre += `<% locals.${key} = (${expr}); %>`;
        }
      }
      return pre + inlinePartials(store[name], store);
    });
  }
  return result;
}

const store = {};
readTemplates(TEMPLATES, store);

const compiled = {};
for (const key of Object.keys(store)) {
  if (key.startsWith('partials/')) continue;
  compiled[key] = inlinePartials(store[key], store);
}

const KEYMAP = {
  index: ['title', 'active', 'ongoing', 'complete', 'eager'],
  anime: ['title', 'active', 'info', 'episodes', 'activeSlug'],
  episode: ['title', 'active', 'activeSlug', 'ep', 'episodes', 'groups'],
  search: ['title', 'active', 'q', 'items', 'eager'],
  list: ['title', 'active', 'kind', 'items', 'page', 'totalPages', 'eager'],
  alist: ['title', 'active', 'items', 'page', 'totalPages'],
  schedule: ['title', 'active', 'days'],
  genres: ['title', 'active', 'genres'],
  error: ['message'],
};

function explicitLocals(tpl, keys) {
  return tpl.replace(/(<%[-=]?)([\s\S]*?)(%>)/g, (m, open, code, close) => {
    let out = code;
    for (const k of keys) {
      out = out.replace(new RegExp('(?<![.\\w])' + k + '\\b(?!\\s*:)', 'g'), 'locals.' + k);
    }
    return open + out + close;
  });
}

fs.mkdirSync(path.join(OUT, 'templates'), { recursive: true });
let body = '// generated by build.js — do not edit\n';
body += 'module.exports = { templates: {\n';
for (const key of Object.keys(compiled)) {
  try {
    const fn = ejs.compile(explicitLocals(compiled[key], KEYMAP[key] || []), { client: true, compileDebug: false, _with: false });
    body += `  ${JSON.stringify(key)}: ${fn.toString()},\n`;
  } catch (err) {
    console.error('COMPILE FAIL:', key);
    console.error(err.message);
    process.exit(1);
  }
}
body += '} };\n';
fs.writeFileSync(path.join(OUT, 'templates', 'templates.cjs'), body);

const assets = {};
for (const file of ['css/tokens.css', 'css/style.css', 'js/app.js']) {
  assets[file] = fs.readFileSync(path.join(PUBLIC, file), 'utf8');
}
fs.mkdirSync(path.join(OUT, 'assets'), { recursive: true });
let ab = '// generated by build.js — do not edit\n';
ab += 'export const assets = {\n';
for (const key of Object.keys(assets)) {
  ab += `  ${JSON.stringify(key)}: ${JSON.stringify(assets[key])},\n`;
}
ab += '};\n';
fs.writeFileSync(path.join(OUT, 'assets', 'assets.js'), ab);

console.log('templates:', Object.keys(compiled).join(', '));
console.log('assets:', Object.keys(assets).join(', '));